version: "3"
services:
  web:
      image: fableguo/my_django
      # volumes:
      #   - api-data:/docker_api
      ports:
        - "8000:8000"
      networks:
        - backend
      deploy:
        replicas: 3
        update_config:
          parallelism: 2
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.backend == backend]
      extra_hosts:
        - "mongo1:192.168.99.106"
        - "mongo2:192.168.99.107"
        - "mongo3:192.168.99.108"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend:

volumes:
  db-data: